#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WellSpring.Droid.Resource", IsApplication=true)]

namespace WellSpring.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::WellSpring.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::WellSpring.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::WellSpring.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::WellSpring.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::WellSpring.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::WellSpring.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::WellSpring.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::WellSpring.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::WellSpring.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::WellSpring.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::WellSpring.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::WellSpring.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::WellSpring.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::WellSpring.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::WellSpring.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::WellSpring.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::WellSpring.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::WellSpring.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::WellSpring.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::WellSpring.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::WellSpring.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Dialog.Droid.Resource.Attribute.MvxBind = global::WellSpring.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Dialog.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::WellSpring.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Dialog.Droid.Resource.Attribute.MvxGroupItemTemplate = global::WellSpring.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Dialog.Droid.Resource.Attribute.MvxItemTemplate = global::WellSpring.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Dialog.Droid.Resource.Attribute.MvxLang = global::WellSpring.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Dialog.Droid.Resource.Attribute.MvxSource = global::WellSpring.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Dialog.Droid.Resource.Attribute.MvxTemplate = global::WellSpring.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Dialog.Droid.Resource.Drawable.dialog_disclosure = global::WellSpring.Droid.Resource.Drawable.dialog_disclosure;
			global::MvvmCross.Dialog.Droid.Resource.Drawable.dialog_expander_ic_minimized = global::WellSpring.Droid.Resource.Drawable.dialog_expander_ic_minimized;
			global::MvvmCross.Dialog.Droid.Resource.Drawable.dialog_icon = global::WellSpring.Droid.Resource.Drawable.dialog_icon;
			global::MvvmCross.Dialog.Droid.Resource.Drawable.dialog_spinner_default_holo_dark = global::WellSpring.Droid.Resource.Drawable.dialog_spinner_default_holo_dark;
			global::MvvmCross.Dialog.Droid.Resource.Drawable.dialog_spinner_default_holo_light = global::WellSpring.Droid.Resource.Drawable.dialog_spinner_default_holo_light;
			global::MvvmCross.Dialog.Droid.Resource.Id.MvvmCrossTagId = global::WellSpring.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Dialog.Droid.Resource.Id.MvxBindingTagUnique = global::WellSpring.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_BoolField = global::WellSpring.Droid.Resource.Id.dialog_BoolField;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_Button = global::WellSpring.Droid.Resource.Id.dialog_Button;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_DisclosureField = global::WellSpring.Droid.Resource.Id.dialog_DisclosureField;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_HtmlField = global::WellSpring.Droid.Resource.Id.dialog_HtmlField;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_ImageLeft = global::WellSpring.Droid.Resource.Id.dialog_ImageLeft;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_ImageRight = global::WellSpring.Droid.Resource.Id.dialog_ImageRight;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelField = global::WellSpring.Droid.Resource.Id.dialog_LabelField;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelPercentageField = global::WellSpring.Droid.Resource.Id.dialog_LabelPercentageField;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelSubtextField = global::WellSpring.Droid.Resource.Id.dialog_LabelSubtextField;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_Panel = global::WellSpring.Droid.Resource.Id.dialog_Panel;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_RadioButtonList = global::WellSpring.Droid.Resource.Id.dialog_RadioButtonList;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_SliderField = global::WellSpring.Droid.Resource.Id.dialog_SliderField;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_Spinner = global::WellSpring.Droid.Resource.Id.dialog_Spinner;
			global::MvvmCross.Dialog.Droid.Resource.Id.dialog_ValueField = global::WellSpring.Droid.Resource.Id.dialog_ValueField;
			global::MvvmCross.Dialog.Droid.Resource.Id.iFormFieldValue = global::WellSpring.Droid.Resource.Id.iFormFieldValue;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_achievements = global::WellSpring.Droid.Resource.Layout.dialog_achievements;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldleft = global::WellSpring.Droid.Resource.Layout.dialog_boolfieldleft;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldright = global::WellSpring.Droid.Resource.Layout.dialog_boolfieldright;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldsubleft = global::WellSpring.Droid.Resource.Layout.dialog_boolfieldsubleft;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldsubright = global::WellSpring.Droid.Resource.Layout.dialog_boolfieldsubright;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_button = global::WellSpring.Droid.Resource.Layout.dialog_button;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_datefield = global::WellSpring.Droid.Resource.Layout.dialog_datefield;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_fieldsetlabel = global::WellSpring.Droid.Resource.Layout.dialog_fieldsetlabel;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_floatimage = global::WellSpring.Droid.Resource.Layout.dialog_floatimage;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_html = global::WellSpring.Droid.Resource.Layout.dialog_html;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_labeldisclosure = global::WellSpring.Droid.Resource.Layout.dialog_labeldisclosure;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_labelfieldbelow = global::WellSpring.Droid.Resource.Layout.dialog_labelfieldbelow;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_labelfieldright = global::WellSpring.Droid.Resource.Layout.dialog_labelfieldright;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_multiline_labelfieldbelow = global::WellSpring.Droid.Resource.Layout.dialog_multiline_labelfieldbelow;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_onofffieldright = global::WellSpring.Droid.Resource.Layout.dialog_onofffieldright;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_panel = global::WellSpring.Droid.Resource.Layout.dialog_panel;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_root = global::WellSpring.Droid.Resource.Layout.dialog_root;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_selectlist = global::WellSpring.Droid.Resource.Layout.dialog_selectlist;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_selectlistfield = global::WellSpring.Droid.Resource.Layout.dialog_selectlistfield;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_textarea = global::WellSpring.Droid.Resource.Layout.dialog_textarea;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_textfieldbelow = global::WellSpring.Droid.Resource.Layout.dialog_textfieldbelow;
			global::MvvmCross.Dialog.Droid.Resource.Layout.dialog_textfieldright = global::WellSpring.Droid.Resource.Layout.dialog_textfieldright;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxBinding = global::WellSpring.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxBinding_MvxBind = global::WellSpring.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxBinding_MvxLang = global::WellSpring.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxControl = global::WellSpring.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::WellSpring.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxExpandableListView = global::WellSpring.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::WellSpring.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxImageView = global::WellSpring.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxImageView_MvxSource = global::WellSpring.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxListView = global::WellSpring.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::WellSpring.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Dialog.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::WellSpring.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::WellSpring.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::WellSpring.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addlight = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_disclosure = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dialog_expander_ic_minimized = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dialog_icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dialog_spinner_default_holo_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int dialog_spinner_default_holo_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int frameborder = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Graphholder = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Iconold = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int IconOri = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int InsertImage = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int mobilemenuicon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int splash = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050030
			public const int DateStr1 = 2131034160;
			
			// aapt resource value: 0x7f050032
			public const int DateStr2 = 2131034162;
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int button1 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int button2 = 2131034117;
			
			// aapt resource value: 0x7f05002c
			public const int clvCalendarView = 2131034156;
			
			// aapt resource value: 0x7f050006
			public const int date = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int datepickertest = 2131034119;
			
			// aapt resource value: 0x7f050020
			public const int dialog_BoolField = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int dialog_Button = 2131034145;
			
			// aapt resource value: 0x7f050026
			public const int dialog_DisclosureField = 2131034150;
			
			// aapt resource value: 0x7f050025
			public const int dialog_HtmlField = 2131034149;
			
			// aapt resource value: 0x7f050023
			public const int dialog_ImageLeft = 2131034147;
			
			// aapt resource value: 0x7f05001e
			public const int dialog_ImageRight = 2131034142;
			
			// aapt resource value: 0x7f05001c
			public const int dialog_LabelField = 2131034140;
			
			// aapt resource value: 0x7f05001f
			public const int dialog_LabelPercentageField = 2131034143;
			
			// aapt resource value: 0x7f05001d
			public const int dialog_LabelSubtextField = 2131034141;
			
			// aapt resource value: 0x7f050027
			public const int dialog_Panel = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int dialog_RadioButtonList = 2131034152;
			
			// aapt resource value: 0x7f050024
			public const int dialog_SliderField = 2131034148;
			
			// aapt resource value: 0x7f050029
			public const int dialog_Spinner = 2131034153;
			
			// aapt resource value: 0x7f050022
			public const int dialog_ValueField = 2131034146;
			
			// aapt resource value: 0x7f050003
			public const int editText1 = 2131034115;
			
			// aapt resource value: 0x7f050031
			public const int endDate = 2131034161;
			
			// aapt resource value: 0x7f05001b
			public const int finishDate = 2131034139;
			
			// aapt resource value: 0x7f050016
			public const int finishdate = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int finishdatepickertest = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int finishtime = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int finishtimepickertest = 2131034137;
			
			// aapt resource value: 0x7f05002a
			public const int iFormFieldValue = 2131034154;
			
			// aapt resource value: 0x7f05000d
			public const int imageButton1 = 2131034125;
			
			// aapt resource value: 0x7f05002f
			public const int imageView1 = 2131034159;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int progressBar1 = 2131034126;
			
			// aapt resource value: 0x7f05002b
			public const int searchView1 = 2131034155;
			
			// aapt resource value: 0x7f05002d
			public const int space1 = 2131034157;
			
			// aapt resource value: 0x7f05001a
			public const int startDate = 2131034138;
			
			// aapt resource value: 0x7f050012
			public const int startdate = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int startdatepickertest = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int starttime = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int starttimepickertest = 2131034133;
			
			// aapt resource value: 0x7f050011
			public const int switch1 = 2131034129;
			
			// aapt resource value: 0x7f05000a
			public const int tableLayout1 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int tableRow2 = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int tableRow4 = 2131034127;
			
			// aapt resource value: 0x7f05002e
			public const int textView1 = 2131034158;
			
			// aapt resource value: 0x7f05000c
			public const int textView5 = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int textView8 = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int time = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int timepickertest = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CommunityAfterConsultView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CommunityConcernView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CommunityConsultView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CommunityCreateMeetupView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CommunityFindMeetupView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CommunityHistoryConsultView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int CommunityMakePostView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int CommunityMeetupView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int CommunityMessageView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int CommunityNurseView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int CommunityView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ConsultationView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int CreateGoalFrame = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int CreateGoalView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_achievements = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_boolfieldleft = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_boolfieldright = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_boolfieldsubleft = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_boolfieldsubright = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int dialog_button = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int dialog_datefield = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int dialog_fieldsetlabel = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int dialog_floatimage = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int dialog_html = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int dialog_labeldisclosure = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int dialog_labelfieldbelow = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int dialog_labelfieldright = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int dialog_multiline_labelfieldbelow = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int dialog_onofffieldright = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int dialog_panel = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int dialog_root = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int dialog_selectlist = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int dialog_selectlistfield = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int dialog_textarea = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int dialog_textfieldbelow = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int dialog_textfieldright = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int exercisesearchlayout = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int GoalView = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int HomeView = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int JourneyCalendarSelectView = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int JourneyComCalendarView = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int JourneyComPlanLayout = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int JourneyComPlanView = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int JourneyCustomFoodView = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int JourneyExercise_RunningView = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int JourneyExercise_WorkoutView = 2130903085;
			
			// aapt resource value: 0x7f03002e
			public const int JourneyExercise_YogaView = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int JourneyExerciseView = 2130903087;
			
			// aapt resource value: 0x7f030030
			public const int JourneyFood_CustomFoodView = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int JourneyFood_FoodView = 2130903089;
			
			// aapt resource value: 0x7f030032
			public const int JourneyFoodInfoView = 2130903090;
			
			// aapt resource value: 0x7f030033
			public const int JourneyFoodView = 2130903091;
			
			// aapt resource value: 0x7f030034
			public const int JourneyOrganiserView = 2130903092;
			
			// aapt resource value: 0x7f030035
			public const int JourneyView = 2130903093;
			
			// aapt resource value: 0x7f030036
			public const int LocationSearchLayout = 2130903094;
			
			// aapt resource value: 0x7f030037
			public const int mealsearchlayout = 2130903095;
			
			// aapt resource value: 0x7f030038
			public const int meetupsearchlayout = 2130903096;
			
			// aapt resource value: 0x7f030039
			public const int RegisterView = 2130903097;
			
			// aapt resource value: 0x7f03003a
			public const int SettingView = 2130903098;
			
			// aapt resource value: 0x7f03003b
			public const int SplashScreen = 2130903099;
			
			// aapt resource value: 0x7f03003c
			public const int StatFrameView = 2130903100;
			
			// aapt resource value: 0x7f03003d
			public const int StatisticsDetailFrameView = 2130903101;
			
			// aapt resource value: 0x7f03003e
			public const int StatisticsDetailView = 2130903102;
			
			// aapt resource value: 0x7f03003f
			public const int StatisticsFrameView = 2130903103;
			
			// aapt resource value: 0x7f030040
			public const int StatisticsPickDateView = 2130903104;
			
			// aapt resource value: 0x7f030041
			public const int StatisticsView = 2130903105;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
